name: CompassPlus
version: ${project.version}
main: me.pinkflameinthepan.compassplus.compassplus.CompassPlus
api-version: 1.16
authors: [pinkflameinthepan]
description: Compass+
commands:
  cplore:
    description: Set the lore for your compass!
    usage: /cplore
    permission: cplus.commands.setCompassLore
